[package]

# Semantic Versioning is used: https://semver.org/
version = "1.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Quadruped Locomotion"
author = "Udula Ranasinghe"
maintainer = "Gavin Kane"
description="Training UnitreeGo2 robot using reinforcement learnig in Isaac Lab"
repository = "https://github.com/UdulaRana/quadruped_go2_locomotion.git"
keywords = ["extension", "template", "isaaclab"]

[dependencies]
"omni.kit.uiapp" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "quadruped_go2_locomotion"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"